-- String Theory — initial schema.
--
-- Design notes
--   * UUID primary keys generated by the database, so an id can never be forged client-side and
--     an insert that fails part-way through a transaction still burns a key rather than a number
--     that a later campaign would otherwise inherit.
--   * `timestamptz` everywhere. `timestamp` without a zone silently means different instants on
--     different hosts, which is exactly the bug that appears after the first deploy.
--   * Enums, not free text, for anything the application branches on. Postgres enums are cheap to
--     read and impossible to typo; adding a value later is an ALTER TYPE, not a data migration.
--   * Every parent/child edge is an explicit foreign key with a deliberate ON DELETE behaviour, so
--     deleting a campaign cannot leave orphaned creative or a brand pointing at a dead user.
--   * updated_at is maintained by a trigger rather than by application code — forgetting it in one
--     of a dozen call sites is not a failure mode worth carrying.

-- gen_random_uuid() is core from PostgreSQL 13 onward; pgcrypto is kept as a no-op guard so the
-- same file applies cleanly to an older cluster or a managed instance with restricted extensions.
CREATE EXTENSION IF NOT EXISTS pgcrypto;

-- ---------------------------------------------------------------------------
-- Roles
-- ---------------------------------------------------------------------------

-- Exactly three account types. ADMIN sees the whole network, BRAND buys screen time, STORE supplies
-- screens. Adding a fourth (e.g. AGENCY) is a one-line ALTER TYPE, not a schema rewrite.
DO $$ BEGIN
  CREATE TYPE user_role AS ENUM ('BRAND', 'STORE', 'ADMIN');
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

-- Lifecycle of a brand account. PENDING_REVIEW until a human clears it, so the moderation step has
-- somewhere to land without a second table.
DO $$ BEGIN
  CREATE TYPE brand_status AS ENUM ('PENDING_REVIEW', 'ACTIVE', 'SUSPENDED');
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  CREATE TYPE store_status AS ENUM ('PENDING_REVIEW', 'ACTIVE', 'PAUSED', 'CLOSED');
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

-- Campaign lifecycle. Deliberately independent of creative state: a campaign can go LIVE with no
-- video attached yet, and can sit DRAFT while a video is still being encoded.
DO $$ BEGIN
  CREATE TYPE campaign_status AS ENUM (
    'DRAFT',
    'IN_REVIEW',
    'SCHEDULED',
    'LIVE',
    'PAUSED',
    'COMPLETED',
    'CANCELLED'
  );
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

-- Video pipeline states, mirroring the architecture in markdown/CONTEXT.md:
--   AWAITING_UPLOAD -> UPLOADING -> UPLOADED -> PROCESSING -> ENCODING -> READY
--   PROCESSING/ENCODING -> RETRYING -> back to PROCESSING/ENCODING, or FAILED after the attempts run out.
-- The states exist now so the pipeline can be bolted on without a migration; nothing in this
-- repository currently writes past AWAITING_UPLOAD.
DO $$ BEGIN
  CREATE TYPE video_status AS ENUM (
    'AWAITING_UPLOAD',
    'UPLOADING',
    'UPLOADED',
    'PROCESSING',
    'ENCODING',
    'RETRYING',
    'READY',
    'FAILED'
  );
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

-- ---------------------------------------------------------------------------
-- updated_at
-- ---------------------------------------------------------------------------

CREATE OR REPLACE FUNCTION st_set_updated_at() RETURNS trigger AS $$
BEGIN
  NEW.updated_at := now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- ---------------------------------------------------------------------------
-- users
-- ---------------------------------------------------------------------------
-- Login identity only. Anything a brand tells us about itself (trading name, website, who to call
-- about an invoice) belongs on `brands`, not here, so the same person can act for more than one
-- brand without duplicating their account.

CREATE TABLE IF NOT EXISTS users (
  id            uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  -- Stored lowercased by the application (lib/validation normalises before insert) so the unique
  -- index below needs no citext extension and case variants cannot create two accounts.
  email         text NOT NULL,
  full_name     text NOT NULL,
  role          user_role NOT NULL,
  phone         text,
  created_at    timestamptz NOT NULL DEFAULT now(),
  updated_at    timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT users_email_blank_chk CHECK (btrim(email) <> ''),
  CONSTRAINT users_email_shape_chk CHECK (position('@' IN email) > 1)
);

CREATE UNIQUE INDEX IF NOT EXISTS users_email_key ON users (email);
-- Role is the primary access-control axis and will be filtered on constantly as the network grows.
CREATE INDEX IF NOT EXISTS users_role_idx ON users (role);

DROP TRIGGER IF EXISTS users_set_updated_at ON users;
CREATE TRIGGER users_set_updated_at BEFORE UPDATE ON users
  FOR EACH ROW EXECUTE FUNCTION st_set_updated_at();

-- ---------------------------------------------------------------------------
-- brands
-- ---------------------------------------------------------------------------
-- The customer record. One row per brand regardless of how many people work there, so campaign
-- history and reporting stay attached to the brand rather than to whoever happened to submit.

CREATE TABLE IF NOT EXISTS brands (
  id                uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  name              text NOT NULL,
  -- Stable, human-readable identifier used in URLs. Derived from name at creation and made unique
  -- by suffix; never shown as the primary id because campaign UUIDs are what links carry.
  slug              text NOT NULL,
  website           text,
  -- Primary point of contact for this brand. NULL only if the owning user account is deleted —
  -- ON DELETE SET NULL keeps the brand and its campaign history while dropping the link.
  owner_user_id     uuid REFERENCES users (id) ON DELETE SET NULL,
  contact_name      text NOT NULL,
  contact_email     text NOT NULL,
  contact_phone     text NOT NULL,
  status            brand_status NOT NULL DEFAULT 'PENDING_REVIEW',
  created_at        timestamptz NOT NULL DEFAULT now(),
  updated_at        timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT brands_name_blank_chk CHECK (btrim(name) <> ''),
  CONSTRAINT brands_slug_blank_chk CHECK (btrim(slug) <> ''),
  CONSTRAINT brands_contact_name_blank_chk CHECK (btrim(contact_name) <> ''),
  -- Application-level check constraints mirror the zod schema; the database stays the last word.
  CONSTRAINT brands_contact_phone_digits_chk CHECK (length(regexp_replace(contact_phone, '[^0-9]', '', 'g')) >= 6),
  CONSTRAINT brands_website_http_chk CHECK (website IS NULL OR website ~* '^https?://')
);

CREATE UNIQUE INDEX IF NOT EXISTS brands_slug_key ON brands (slug);
CREATE INDEX IF NOT EXISTS brands_owner_user_id_idx ON brands (owner_user_id);
CREATE INDEX IF NOT EXISTS brands_status_idx ON brands (status);

DROP TRIGGER IF EXISTS brands_set_updated_at ON brands;
CREATE TRIGGER brands_set_updated_at BEFORE UPDATE ON brands
  FOR EACH ROW EXECUTE FUNCTION st_set_updated_at();

-- ---------------------------------------------------------------------------
-- stores
-- ---------------------------------------------------------------------------
-- A venue that supplies screens. The table is created now so role-based access and the discovery
-- flow have a target, but nothing in this repository writes to it yet — a store is onboarded in a
-- later phase, not through the campaign form.

CREATE TABLE IF NOT EXISTS stores (
  id                uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  name              text NOT NULL,
  slug              text NOT NULL,
  website           text,
  owner_user_id     uuid REFERENCES users (id) ON DELETE SET NULL,
  contact_name      text,
  contact_email     text NOT NULL,
  contact_phone     text,
  status            store_status NOT NULL DEFAULT 'PENDING_REVIEW',
  created_at        timestamptz NOT NULL DEFAULT now(),
  updated_at        timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT stores_name_blank_chk CHECK (btrim(name) <> ''),
  CONSTRAINT stores_slug_blank_chk CHECK (btrim(slug) <> ''),
  CONSTRAINT stores_contact_email_shape_chk CHECK (position('@' IN contact_email) > 1),
  CONSTRAINT stores_website_http_chk CHECK (website IS NULL OR website ~* '^https?://')
);

CREATE UNIQUE INDEX IF NOT EXISTS stores_slug_key ON stores (slug);
CREATE INDEX IF NOT EXISTS stores_owner_user_id_idx ON stores (owner_user_id);
CREATE INDEX IF NOT EXISTS stores_status_idx ON stores (status);

DROP TRIGGER IF EXISTS stores_set_updated_at ON stores;
CREATE TRIGGER stores_set_updated_at BEFORE UPDATE ON stores
  FOR EACH ROW EXECUTE FUNCTION st_set_updated_at();

-- ---------------------------------------------------------------------------
-- campaigns
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS campaigns (
  id            uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  brand_id      uuid NOT NULL REFERENCES brands (id) ON DELETE CASCADE,
  -- Unique per brand rather than globally: two brands may legitimately both run a "Spring Launch",
  -- but one brand may not have two campaigns with the same slug in its own detail URLs.
  slug          text NOT NULL,
  name          text NOT NULL,
  description   text,
  status        campaign_status NOT NULL DEFAULT 'DRAFT',
  starts_on     date,
  ends_on       date,
  -- Who pressed the button. SET NULL rather than CASCADE because losing a user account must not
  -- delete a campaign that a brand is still billing against.
  created_by    uuid REFERENCES users (id) ON DELETE SET NULL,
  created_at    timestamptz NOT NULL DEFAULT now(),
  updated_at    timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT campaigns_name_blank_chk CHECK (btrim(name) <> ''),
  CONSTRAINT campaigns_slug_blank_chk CHECK (btrim(slug) <> ''),
  CONSTRAINT campaigns_date_order_chk CHECK (ends_on IS NULL OR starts_on IS NULL OR ends_on >= starts_on)
);

CREATE UNIQUE INDEX IF NOT EXISTS campaigns_brand_slug_key ON campaigns (brand_id, slug);
-- Every campaign list and brand detail page is "this brand's campaigns, newest first".
CREATE INDEX IF NOT EXISTS campaigns_brand_id_created_at_idx ON campaigns (brand_id, created_at DESC);
CREATE INDEX IF NOT EXISTS campaigns_status_idx ON campaigns (status);
CREATE INDEX IF NOT EXISTS campaigns_created_by_idx ON campaigns (created_by);

DROP TRIGGER IF EXISTS campaigns_set_updated_at ON campaigns;
CREATE TRIGGER campaigns_set_updated_at BEFORE UPDATE ON campaigns
  FOR EACH ROW EXECUTE FUNCTION st_set_updated_at();

-- ---------------------------------------------------------------------------
-- campaign_videos
-- ---------------------------------------------------------------------------
-- Creative attached to a campaign. Currently the only thing written here is the placeholder row for
-- the file a browser *offered* us — no bytes, no S3 key, no upload. The shape below is already the
-- final one, so the pipeline lands as writes rather than as a migration:
--
--   1. client -> presigned PUT -> original_bucket/original_key, status UPLOADED
--   2. worker  -> ffprobe into width/height/duration_seconds/codec, status PROCESSING
--   3. worker  -> transcode to H.264 into encoded_bucket/encoded_key, status READY
--
-- attempt_count and last_error back the RETRYING state with exponential backoff.

CREATE TABLE IF NOT EXISTS campaign_videos (
  id                uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  -- One active creative per campaign for now. A unique constraint rather than a plain index, so
  -- "the video for this campaign" is an unambiguous lookup and a second insert fails loudly.
  campaign_id       uuid NOT NULL UNIQUE REFERENCES campaigns (id) ON DELETE CASCADE,

  -- What the browser said it was sending. Advisory until the pipeline uploads and verifies bytes.
  source_filename   text NOT NULL,
  source_mime_type  text,
  source_bytes      bigint,

  -- Pipeline state. Defaults to the only value this codebase can actually produce.
  status            video_status NOT NULL DEFAULT 'AWAITING_UPLOAD',

  -- S3 locations. All NULL until the upload pipeline exists; every column is nullable on purpose so
  -- the placeholder insert needs no sentinel values.
  original_bucket   text,
  original_key      text,
  encoded_bucket    text,
  encoded_key       text,

  -- Encoder output facts, filled in by the future transcode worker. codec is expected to be 'h264'.
  width             integer,
  height            integer,
  duration_seconds  numeric(10, 3),
  codec             text,
  bitrate_kbps      integer,

  attempt_count     integer NOT NULL DEFAULT 0,
  last_error        text,

  uploaded_at       timestamptz,
  encoded_at        timestamptz,
  ready_at          timestamptz,
  created_at        timestamptz NOT NULL DEFAULT now(),
  updated_at        timestamptz NOT NULL DEFAULT now(),

  CONSTRAINT campaign_videos_filename_blank_chk CHECK (btrim(source_filename) <> ''),
  CONSTRAINT campaign_videos_bytes_nonneg_chk CHECK (source_bytes IS NULL OR source_bytes >= 0),
  CONSTRAINT campaign_videos_attempt_nonneg_chk CHECK (attempt_count >= 0),
  CONSTRAINT campaign_videos_dimensions_chk CHECK (
    (width IS NULL OR width > 0) AND (height IS NULL OR height > 0)
  ),
  -- A video cannot be READY without both the transcoded object and the facts describing it.
  CONSTRAINT campaign_videos_ready_chk CHECK (
    status <> 'READY' OR (encoded_key IS NOT NULL AND codec IS NOT NULL AND ready_at IS NOT NULL)
  )
);

-- The pipeline polls for work by state; without this the queue is a sequential scan of the table.
CREATE INDEX IF NOT EXISTS campaign_videos_status_idx ON campaign_videos (status);

DROP TRIGGER IF EXISTS campaign_videos_set_updated_at ON campaign_videos;
CREATE TRIGGER campaign_videos_set_updated_at BEFORE UPDATE ON campaign_videos
  FOR EACH ROW EXECUTE FUNCTION st_set_updated_at();